set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSROOT "/toolchain/sysroots/cortexa53-poky-linux")
set(CMAKE_C_COMPILER "/toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc")
set(CMAKE_CXX_COMPILER "/toolchain/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++")
set(OE_QMAKE_PATH_EXTERNAL_HOST_BINS "/toolchain/sysroots/x86_64-pokysdk-linux/usr/bin")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
